wandb_version: 1

Batch size:
  desc: null
  value: '64'
Criterion:
  desc: null
  value: FocalLoss
Image shape:
  desc: null
  value: 224,224
Learning rate:
  desc: null
  value: '0.0001'
Metric:
  desc: null
  value: None
Model:
  desc: null
  value: efficientnet_b3_pruned
Optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/baseline/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1646408810
    t:
      1:
      - 1
      - 5
      - 30
      - 41
      2:
      - 1
      - 5
      - 30
      - 41
      3:
      - 13
      4: 3.8.12
      5: 0.12.11
      8:
      - 5
